@startuml
left to right direction
skinparam actorStyle awesome

actor "Member" as member

member --> (Log in or register)
member --> (View profile)
(View profile) <.. (Change profile) : <<extend>>
(View profile) <.. (Change password) : <<extend>>
member --> (View personal Announcement)
member --> (Track progress)
member --> (Schedule a workout)
member --> (Shop cart)
member --> (Register training package)
member --> (Payment)
(Payment) <.. (Shop cart) : <<extend>>
(Payment) <.. (Register training package) : <<extend>>
(Payment) <.. (Payment history) : <<extend>>
(Payment) ..> (Confirm transaction) : <<include>>

@enduml

@startuml
left to right direction
skinparam actorStyle awesome

actor "Trainer" as trainer

trainer -> (Log in or register)
trainer --> (View profile)
(View profile) <.. (Change profile) : <<extend>>
(View profile) <.. (Change password) : <<extend>>
trainer --> (View work schedule)
trainer --> (View group class)
(View group class) <.. (Attendance report): <<extend>>
(View work schedule) --> (CRUD)
trainer --> (Report equipment issues)

@enduml

@startuml
left to right direction
skinparam actorStyle awesome

actor "Inventory" as inventory

inventory -> (Log in or register)
inventory --> (View profile)
(View profile) <.. (Change profile) : <<extend>>
(View profile) <.. (Change password) : <<extend>>
inventory --> (View products)
(View products) --> (CRUD)
inventory --> (View equipment and facility)
(View equipment and facility) --> (CRUD)

@enduml

@startuml
left to right direction
skinparam actorStyle awesome

actor "Admin" as admin

admin -> (Log in or register)
admin --> (View profile)
(View profile) <.. (Change profile) : <<extend>>
(View profile) <.. (Change password) : <<extend>>
admin --> (Overview Dashboard)
admin --> (View account)
(View account) --> (CRUD)

@enduml

@startuml
left to right direction
skinparam actorStyle awesome

actor "Manager" as manager

manager -> (Log in or register)
manager --> (View profile)
        (View profile) <.. (Change profile) : <<extend>>
        (View profile) <.. (Change password) : <<extend>>

manager --> (View statistics and reports)
(View statistics and reports) <.. (Create statistics and report) : <<extend>>
(View statistics and reports) <.. (View payment history) : <<extend>>
(View statistics and reports) <.. (Verify and confirm transaction status) : <<extend>>

manager --> (View group class)
(View group class) <.. (Attendance report): <<extend>>
(View group class) --> (CRUD)

manager --> (View work schedule)
(View work schedule) --> (CRUD)

manager --> (View training package)
(View training package) --> (CRUD)


manager --> (View products)
(View products) --> (CRUD)

manager --> (View equipment and facility)
(View equipment and facility) --> (CRUD)

manager --> (View promotion and discount)
(View promotion and discount) --> (CRUD)

manager --> (View notification event)
(View notification event) --> (CRUD)

@enduml
